#!/bin/sh

#---------------------------------------------------------------------
# install dependencies
apk add \
    make \
    docker \
    git \
    curl

pip3 install --upgrade pip wheel setuptools && pip3 --version
python3 -V
pip3 -V
pip3 install \
    packages/simcore-sdk \
    docker-compose

docker -v
docker-compose -v

