#!/bin/bash
cd $(dirname $0)
# ----------------------------------------------------------------
# This script shall be modified according to the needs in order to run the service
# The inputs defined in docker/inputs.json are available as env variables by their key in capital letters
# For example: input_1 -> $INPUT_1
# call stack:
# run -> do_run -> execute

set -e
cd $HOME/{{ cookiecutter.project_package_name }}
# put the code to execute the service here
# and default all outputs to $LOG_FILE
# For example: java someJavaClass >> $LOG_FILE

# then retrieve the output and move it to the $OUTPUT_FOLDER
# as defined in the output labels
# For example: cp output.csv $OUTPUT_FOLDER or to $OUTPUT_FOLDER/output.json using jq
